### ISSUE TITLE
Add algo ‘randomepic’ algorithm (EpicCash RandomX)

### ISSUE THREAD

**Issue by whereveryouare666** [xmrig/xmrig#3282] opened 2023-06-03 10:24 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Required data**
 - Miner log as text or screenshot
 - Config file or command line (without wallets)
 - OS: [e.g. Windows]
 - For GPU related issues: information about GPUs and driver version.

**Additional context**

**Comment by koitsu** [comment] 2023-06-14 16:09
Looks like a duplicate of https://github.com/xmrig/xmrig/issues/3248

**Closed** 2023-06-21 10:53 UTC
