### ISSUE TITLE
how to disable stdout in background=true mode? 

### ISSUE THREAD

**Issue by qutimqqcom** [xmrig/xmrig#1141] opened 2019-08-27 09:33 UTC
previos version work silent

**Comment by xmrig** [comment] 2019-08-27 21:22
I can't reproduce the issue, please provide more details.
Thank you.

**Comment by qutimqqcom** [comment] 2019-08-28 09:38
setup daemon mode using "background": true,
process fall to background 
but  logs appear  in console 

 * ABOUT        XMRig/3.1.0 gcc/7.4.1
 * LIBS         libuv/1.30.1 hwloc/1.11.8rc2-git
 * CPU          Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (1) x64 AES
                L2:1.0 MB L3:8.0 MB 4C/8T NUMA:1
 * DONATE       5%
 * ASSEMBLY     auto:intel
 * POOL #1      111.22.22.1:10016 algo auto
 * COMMANDS     hashrate, pause, resume

[2019-08-28 12:31:21.667] use pool 111.22.22.1:10016  111.22.22.1
[2019-08-28 12:31:21.667] new job from 111.22.22.1:10016 diff 500 algo cn/r height 1910587
[2019-08-28 12:31:21.667]  cpu  use profile  cn/r  (2 threads) scratchpad 2048 KB
[2019-08-28 12:31:22.166]  cpu  READY threads 2(2) huge pages 2/2 100% memory 4096 KB (499 ms)
[2019-08-28 12:31:33.896] accepted (2/0) diff 500 (196 ms)
[2019-08-28 12:31:33.961] accepted (3/0) diff 500 (94 ms)

**Comment by xmrig** [comment] 2019-08-30 06:59
I can't reproduce the issue, for me option `background` works fine, please provide all details, what OS do you use, how exactly option set: config, command line or mixed, etc.
Thank you.

**Comment by xmrig** [comment] 2019-08-30 07:16
Okay, fine I got this issue, this happen if no other logs options specified, `log-file` or `syslog`.

**Comment by xmrig** [comment] 2019-08-30 07:47
Fixed in dev branch.

**Comment by qutimqqcom** [comment] 2019-08-30 18:44
> Fixed in dev branch.

Can users take the dev version for the build?

**Comment by xmrig** [comment] 2019-08-30 22:33
https://buildbot.xmrig.com/#/ every commit in master, dev, evo and beta branches has binary builds also I will make v3.1.1 release soon.

**Comment by xmrig** [comment] 2019-08-31 02:01
https://github.com/xmrig/xmrig/releases/tag/v3.1.1

**Closed by xmrig** 2019-08-31 02:01 UTC
Labels: bug
