### ISSUE TITLE
Inconsistant benchmark numbers (v2.4.0)

### ISSUE THREAD

**Issue by pjdouillard** [xmrig/xmrig#207] opened 2017-11-19 07:38 UTC
Hello,

I am using an i7-8700k (not OC but core enhancement active, so that's all core at 4.7Ghz - system is watercooled, relidded with liquiq-metal, and it runs at 50C under full load (that's 30C vs the toothpaste Tim) and I am getting very inconsistant benchmark numbers with the algo.  

Under Win 10, with no activity else the benchmarking via Nicehash interface, I get speed ranging from 440 to as low as 192 - with no parametrisation whatsoever.   At some point, I thought the cpu was "broken" because next to it is another system with an old i7-980x (another 6-core with HT enabled) that performs flawlessly at 262.  Another system with 2 old Xeon X5690 performs both at 243.

Sometimes, when I do run the algo to mine, it gets only 3 threads, other times it get 6.  Sometime those 6 threads give 200 H/s, and some other time 360.

So I dig and found I could setup cpu affinity (which I did) but I can't get better than 363 with a mask of 0x0555 (0000 0101 0101 0101).

Is there something I am missing here, or this cpu is just too fast for proper benchmarking?

I am open to help test code for you against this cpu if you need, because this baby is a jewel of speed.

While typing this, I re-did another benchmark, now I got 475...

When I received my Ryzen back from AMD (RMA'd for the segfault-bug), I hope numbers will less fluctuate.

**Comment by gryle** [comment] 2017-11-20 10:50
Hi

I have the same issue with a coffee lake i5 8600k.
Sometimes the hashrate is 140, sometimes 220 and other times 310H/s
I thaught there was some issue with my new system

**Comment by gennadicho** [comment] 2017-11-22 23:49
@gryle set up monitoring on your system, and look for another process who eating CPU.

**Comment by gryle** [comment] 2017-11-23 16:54
The only way to solve it is restarting xmrig until it gets the good hashrate.
Using the RAMMap utility from sysinternals and it's various "Empty..." options between restarts helps also

**Comment by pjdouillard** [comment] 2017-11-23 17:57
On the 5 systems I am using the algo on, all with Win 10, only this one is doing this.  All other systems have their Win 10 installed since quite a while now vs the 8700k who is kind of fresh (3-4 weeks).  

The CPU of the other systems are 980X, 5690X (dual), 4790k and a Ryzen 7 1800X.  
None of those are behaving like that.  
Speed I have on the CPUs while running:
980X : 260 H/s
5690X (dual) : 265 H/s (on each cpu)
4790k: 325 H/s
1800X : 530 H/s

When the cpu gets bugged down on those machines, the H/s goes down, but as soon as the cpu freed itself, the H/s rises again to its usual speed.  

While continue to investigate and come back when I have something.

**Comment by gryle** [comment] 2017-11-24 00:26
This issue seems specific to the new intel coffee lake CPUs.
I don't have this issue on other systems, one with an i5 3570k and another with an i5 4690.

**Comment by pjdouillard** [comment] 2017-11-27 17:08
Can you - and others also - post your benchmark vs your cpu@xGhz please and how many threads you are running please?  I am testing each system individually from 1 to 12 threads and nothing their speeds and where it seems (sometimes - not always) where performance drops (or diminishing return) as you increase the number of threads.

Will post back with my outputs.

**Comment by travisdietrich** [comment] 2017-12-01 14:54
Just wanted to post that I'm seeing this same issue on my 8700k.  Hash from 280 - 400, hash rate stays stable at whatever rate it picks and doesn't move unless I restart the miner.

I was previously running a Ryzen 1600X and never saw this issue, speed was always consistent.

I just swapped my motherboard and processor and didn't reinstall, so programs running in the background isn't the issue.  Same exact setup as previously running the old processor.

**Comment by pjdouillard** [comment] 2017-12-01 15:59
On my 1800X@4Ghz, although sometimes it starts low, it climbs its way back to around 630-650 H/s eventually (with large pages and 8 threads - affinity set or not).

On the old Intel Gulftown/Westmere cpu (980X and X5690 Xeon), output is always the same at around 260-265 H/s with large page and 6 threads.

On the 4790k, I see the same kind of behavior as on the 8700k : on a 'good' start, it get 340 H/s (with large pages) or it can stick to low output at 220ish and stay there forever.  If I manually ramp up its threads, it finally reaches its 320-360 H/s with LP active.


Best I can get on the 8700k@5Ghz + large pages is around 450 H/s on a 'good' start.

When I 'crank' up the threads manually, it reaches around it best speed of 450 H/s as we can see here:

1 thread:
[2017-12-01 10:30:02] speed 2.5s/60s/15m 90.2 n/a n/a H/s max: 90.3 H/s

2 threads:
[2017-12-01 10:31:55] speed 2.5s/60s/15m 171.5 n/a n/a H/s max: 172.7 H/s

3 threads:
[2017-12-01 10:33:04] speed 2.5s/60s/15m 267.0 n/a n/a H/s max: 266.9 H/s

4 threads:
[2017-12-01 10:34:20] speed 2.5s/60s/15m 351.2 n/a n/a H/s max: 351.0 H/s

5 threads:
[2017-12-01 10:34:55] speed 2.5s/60s/15m 414.6 n/a n/a H/s max: 413.9 H/s

6 threads:
[2017-12-01 10:37:32] speed 2.5s/60s/15m 456.7 455.3 n/a H/s max: 456.3 H/s

I haven't check the code, so I don't know if it is done or not in it, but maybe some benchmark phase should be made with only 1 thread to have a ballpark figure of what N thread (minus some % of efficiency) should be. 

For example, let us say that a 1 thread bench on the 8700k is 85 H/s.  Theoretically, 6 threads would yield around 510 H/s in a perfect world but that is not possible due to OS overhead and other processes taking cpu time it will necessarily be lower.

In my case, 450 H/s seems the maximum I could reach with 6 threads so that is a 75% efficiency rating.

So if a system system with allocated N threads to the algo is performing at less then 75%  (ex: 1 thread bench is 50 H/s and the algo is asked to run with 3 threads => 3 x 50 H/s = 150 H/s @ 75% = 112 H/s) then we should warn the user that either the system is being used too much by other processes and the number of threads should be reduced.

The other things that is running in the back of my head is that the L3 cache is not able to load the entirety of its job workload and thus that why we see threads outputting only half of what they normally should.  Then maybe a pre-load should be done to get the cache a speed and force it to actully 'cache' what needs to be loaded.  That way, there won't be any slowdown.  That's what we went we ramp up on the number of threads as the cache is 'getting ready'.

Or, threads are not launched all at the same time like it seems to be the case.  Instead they are launched one at a time so that each threads can allocated the L3 cache properly and starts to work near (@75% efficiency) of the 1-thread bench mark.  That way, I am sure we would not see such discrepancies between run and we would get way better stable numbers and efficiency.  Right now, it is a bit of a lottery so see if the L3 cache will be load up properly on those cpu.

Any thoughts?

**Comment by HansHagberg** [comment] 2017-12-16 01:43
Same issues here on a fresh i5-8600K rig. Installed latest Win 10 just 2 hours ago and XMRig was the first thing I tried after installing all drivers and stuff. Not even a GPU yet in the system.

I got around 225 at first attempt. Enabled huge pages, rebooted and then it wont go past 130.
This is with 4 threads. This CPU has 9MB L3 cache so that should be optimal.
2 cores doing nothing so definitely no extra CPU load causing this.

I have another coffee machine (I3-8350K) running at same frequencies but 3 threads producing 240 MH/s so I know the new machine does not perform properly.

**Comment by pjdouillard** [comment] 2017-12-16 02:02
Lately, I have used a tool called Process Lasso to force everything to run on HT core #0 & #1 (i.e. Windows process and the GPU mining process & threads), and force 5 threads of xmrig to run on the 5 remaining cores.  I was able again to reach 400ish H/s this way 'forcefully'.

What I am starting to think is those 8700/8600 CPU from Intel are not behaving like the previous gen.  I will say that even after rebooting and letting Windows 10 'sink in' for a few min of idling, 60% of the time I can't reach the maximum 450 H/s with just xmrig running.  

On those occasion that I can't get a good hash rate, I ramp up the threads one by one.  One, two and three threads gives me the maximum number of H/s for their thread count, but as soon as I go pass 3 threads, the H/s goes down and is lower sometimes then 2 threads **on a 6-core cpu**.  I just can't explain what is going on.

There is really something weird with these chip.  The same thing happens with xmr-stak so it is not I am discarding the problem coming from xmrig.

On the Ryzen side, on the 4GHz 1800X, xmrig alone reaches 660 H/s (or 600 H/s stock clock)
My old 4790k (stock clock) with xmrig alone reachs 350 H/s without any retries or ramp up.

Will be interesting to see

**Comment by MaKla89** [comment] 2018-02-23 17:29
Sorry for digging in this old thread, but is there any update on the matter? :/ 
I just got my 8600k yesterday (after I've been playing around with xmrig for quite a while) and my system behahves like this:

i5 8600k @ 4,7 GHz (OC'ed) / 1,28 VCore

10% of all XMRIG-starts: about 120 H/s
80% of all XMRIG-starts: about 230 H/s
10% of all XMRIG-starts: about 340 H/s (!!)

The "decision" about WHICH of these states is being picked seems to be done the very instant I start XMRIG and won't change within any given time (even over night). I'd be quite happy about 340 H/s (if minnig would have been my only goal I'd have gone for Ryzen, but I like the intel parts :D) , but this completely annoying inconsistency really blows :(

**Comment by gryle** [comment] 2018-02-24 22:52
No update that I know of :(
I seem to have better luck in getting 300H/s by running xmrig on windows startup

**Comment by xmrig** [comment] 2018-03-14 23:51
Definitely something wrong with 8*** CPUs.
Thank you.

**Comment by pjdouillard** [comment] 2018-03-15 00:35
I am really starting to believe the 8000 series didn't follow the same '6-core' design of previous gen (or any gen for the matter).  It migh be an 8-core with 2 disabled cores and the frequency upped for higher IPC but somehow, the available 12MB cache isn't always fully available which would explain those drops.

That would somewhat explain that with 4 threads you often get the best hashrate at any given time, but you have to stop restart continuously with 5,6-core to get the optimal 440+ish hashrate that occurs once every full moon.  It's just speculation I know, but any other Intel 6-core cpus don't behave like that: they are consistaly reaching their optimal hashrare, whenever you lunch xmrig (same thing with Ryzen 8-core chip).

**Comment by MaKla89** [comment] 2018-03-15 06:05
Hm, either I'm more lucky over the last days or something changed: 5 out of 5 times in a row I reached 310 H/s without having to restart the miner at all :D I only updated the NiceHash Legacy miner, but I guess that cannot really be the origin of this improvement..

**Comment by bmatthewshea** [comment] 2018-07-07 16:41
Yeah.. my 8700k/Coffeelake gets 400H using 5/6 cores (via configured threads).
But, it gets 320-330H if using all 6 cores/same configs. So.. I'm missing about 80h when all cores selected?
Occasionally, it will run at about 400-420h (starting it on all 6 cores). But i haven't seen it do that in a awhile. Running on 5 cores for now..

**Comment by tarvcode** [comment] 2018-07-08 23:04
For what it's worth.
I've been having decent success getting maximum hash rate by doing the following...

1) Start XMRIG and let it run for about a minute, then
2) Start another instance of XMRIG and let it run for a minute as well, then
3) Exit the first instance of XMRIG and wait 30 seconds, check hash rate of remaining instance.
4) If hash rate isn't where it should be (around 430h), go back to step 2.

Usually works in the first three tries.  Works best if the computer has just been restarted and you aren't trying to multi-task while doing this.

**Comment by bmatthewshea** [comment] 2018-08-24 02:15
Thanks for tip @tarvcode , but I had that work like that maybe twice - sat here like 20-30 mins trying - sometimes "never" works. I think it's just a roll of dice to be honest.
Almost always starts at 330H for me - occasionally lower.

https://i.imgur.com/qPF4tyd.png

Those ^ -all- should all be in the 80s on default settings.
They never are. It may show them on different cores on restarts but always 2 high, the rest "low".

**Comment by tarvcode** [comment] 2018-08-24 17:32
@bmatthewshea a few differences on my config.  I limit to five threads (six makes no difference) and specify affinity to make sure it's spread out on all the cores and not a hyperthread core.

`--threads=5 --cpu-priority=0 --cpu-affinity=0xAAA --max-cpu-usage=50`

![image](https://user-images.githubusercontent.com/16649815/44598763-b1d28980-a799-11e8-8edf-a16be402e407.png)


The rest of these tips, YMMV;

Luck will drop to get that 430h/s if I'm running other programs, Chrome especially.   Fresh reboot seems to work best, or close everything.

Waiting 30 seconds or so between launching and closing seems to work best.  IE: Launch first instance, wait 30, launch 2nd instance, wait 30, close 1st instance, wait 30.  If no go, launch 2nd instance again and wait 30.  3 or 4 tries should do her.

**Comment by bmatthewshea** [comment] 2018-08-25 15:47
Had some luck killing/closing processes.
One culprit I think was the "Windows Modules Installer" service running at 10% load continually I had not noticed previously. (-> No windows updates are available - it's up-to-date. Not sure why it does that. Typical MS Windows, though..)

Anyway, killed that off that and waited till system was in 'calm' state as much as possible.
and:
![image 3](https://user-images.githubusercontent.com/984097/44619903-b2c6f200-a851-11e8-8f5e-032959ea4b18.png)
(Seen it higher, but good enough.)
Killed that.
Ran chrome. Waited a minute.
Started miner. 330h.
Closed Chrome waited for 'calm' (~30-60 secs.)
Started a new miner window and got ~430 again.
Maybe isn't reproducible 100%, but I have a bit more confidence that may be the 'issue'.

At any rate, this CPU problem needs to be addresses in code. It's still very annoying.

And if you automate things you can never guarantee the miner will (re)start at max level.

No other CPU I have does this w/ xmrig/xmr-stak. Does anyone have an idea on what is going on with the 8700? Articles (Intel)? 'Weird' cache (L2/L3) problems as proposed/mentioned? I have googled and don't see much. Just more guessing.

Seems to me If we don't even know what the issue really is (literally all I have seen are guesses), there is no way it will ever be addressed it this code or others.. just my 1.5 cents.

**Comment by apl-git** [comment] 2018-10-03 23:28
Any updates on this bug? Any estimations when, in which version will it be fixed? The bug can be easily reproduced in version 2.6.4 on my i5-8600K, under Ubuntu 16.04 and 18.04. Hashrate can take any values between 120 H/s and 300 H/s, but most of the times it is around 200 H/s. Getting 200 H/s is relatively easy, but getting 300 H/s usually takes several hours of babysitting the program.

**Closed** 2019-12-22 19:20 UTC
Labels: bug
