### ISSUE TITLE
any help to add default configuration "pool & user " in source code to use just the compiled binary without config.json

### ISSUE THREAD

**Issue by hyassine53** [xmrig/xmrig#136] opened 2017-10-02 15:35 UTC
i am not expert on c++ but i wish to get some help 
i wanna compile the source code with default configuration " pool and port and password" to run just the binary 
i did some changes on the source code in Url.cpp and Url.h but i still cant compile it

**Comment by xxaamm** [comment] 2017-10-02 15:40
I have done that in my fork. Take a look at the below changes. 

The defaults are specified in the Url.h in these lines:
https://github.com/xxaamm/xmrig/blob/55965cb10022d31a8e88a63360e68526ef356b03/src/net/Url.h#L34

Refer to them in Options.cpp:
https://github.com/xxaamm/xmrig/blob/55965cb10022d31a8e88a63360e68526ef356b03/src/Options.cpp#L204

**Comment by hyassine53** [comment] 2017-10-02 18:38
thank you for the solution
now its working

**Comment by sunk818** [comment] 2017-10-30 07:09
duplicate of #109

**Closed** 2017-11-27 00:36 UTC
