### ISSUE TITLE
5.3.0 crashing after running in administrator mode Ryzen 1700x

### ISSUE THREAD

**Issue by DCress12** [xmrig/xmrig#1425] opened 2019-12-15 20:14 UTC
xmrig crashes after I right click run as administrator on xmrig.exe. It is running on Ryzen 1700x

It runs fine if a double left click to run but get the yellow warning that it needs to be run as administrator.

A have a 2nd machine running a Ryzen 3900x this is running with out a problem on 5.3.0 as administrator.

**Comment by SChernykh** [comment] 2019-12-15 22:04
MSR mod appears to enable Opcache, so if you had it disabled in BIOS for 1700X to fix crashes, you can't use MSR mod unfortunately. Try with `"wrmsr":false` in config.json

**Comment by DCress12** [comment] 2019-12-15 22:27
You are correct that I have needed to disable Opcache.

 "wrmsr":false has stopped the crash when run as administrator but it is giving me lower h/s

**Comment by GjBrutello** [comment] 2019-12-16 00:10
Many old Xeon E56.. processors have about the same issue, if xmrig.exe running as Services (system account) or added to schtasks with high privileges it get crash after 2-3 min. "wrmsr":false did not help. Now to be logged as user to work it perfectly.

**Comment by aa-delite** [comment] 2019-12-16 00:37
Confirmed, have also Ryzen 1700X. Opcache disabled, but 5.3.0 crashes anyway. With or without WinRing0x64.sys.
5.1.0 works fine with Opcache disabled.

**Comment by SChernykh** [comment] 2019-12-17 06:23
Note that you need to reboot once you've run 5.3.0 with MSR mod enabled. Opcache stays enabled until reboot after that.

**Comment by DCress12** [comment] 2019-12-17 08:00
> Note that you need to reboot once you've run 5.3.0 with MSR mod enabled. Opcache stays enabled until reboot after that.

Sorry I do not understand this. Could you reword it. Thanks.

**Comment by SChernykh** [comment] 2019-12-17 08:09
If you run 5.3.0 and get crashes on 1700X, all other version will start crashing too until you reboot.

**Comment by DCress12** [comment] 2019-12-17 17:16
I can get 5.3.0 running without problems. The problem is that it will crash if I run as administrator to allow MSR write so I would like to get the write MSR registers to work.

**Comment by SChernykh** [comment] 2019-12-17 17:27
Yes, I'm working on it. I just need to find out which bit in MSR registers is responsible for Opcache on/off. Can you download dev buid from here: https://download.xmrig.com/xmrig/5.4.0-dev/3cc8b19ca00191241fedfbec152df0b1c787444d/ (user: `xmrig`, password: `download`), set `"verbose":1` in config.json (at the bottom), `"url": "randomx-benchmark.xmrig.com:7777"` then run it as administrator with Opcache disabled in BIOS, then paste here full console output? Then reboot, enable Opcache in BIOS, repeat and paste full console output again? I just need to compare MSR register values with Opcache on/off.

**Comment by DCress12** [comment] 2019-12-17 17:35
Will get on it tonight. Can you tell me how to do the full console output thing?

Thanks for your time :)

**Comment by SChernykh** [comment] 2019-12-17 17:39
You can just make a screenshot of XMRig window, I only need to see all MSR register values on this screenshot.

**Comment by DCress12** [comment] 2019-12-17 19:53
Opcache disabled

![xmrig Opcache disabled](https://user-images.githubusercontent.com/49696768/71029121-a2055400-2106-11ea-9d02-6dac5920be07.jpg)

Opcache enabled]

![xmrig Opcache enabled](https://user-images.githubusercontent.com/49696768/71029188-c7925d80-2106-11ea-81e0-f0083ad38525.jpg)

**Comment by xmrig** [comment] 2019-12-17 19:59
@DCress12 Can you make screenshot with disabled Opcache again, it looks like it not first miner run after reboot, only first run required, because MSR mod values already applied, if miner crash it not revert initial values.
Thank you.

**Comment by DCress12** [comment] 2019-12-17 20:10
> @DCress12 Can you make screenshot with disabled Opcache again, it looks like it not first miner run after reboot, only first run required, because MSR mod values already applied, if miner crash it not revert initial values.
> Thank you.

To confirm you want me to disable Opcache  and run as administer?

**Comment by xmrig** [comment] 2019-12-17 20:15
Yes disable Opcache, then screenshot before miner crashed, if it crashed before you make screenshot reboot and try again.
Thank you.

**Comment by DCress12** [comment] 2019-12-17 20:24
![xmrig Opcache disabled 02](https://user-images.githubusercontent.com/49696768/71031374-2954c680-210b-11ea-8680-97ec68566954.jpg)

**Comment by aa-delite** [comment] 2019-12-17 20:25
![NOT_CLEAN_RESTART_opcache_off1](https://user-images.githubusercontent.com/20845944/71031307-f293a600-2134-11ea-97bf-b6597bf80325.png)
![CLEAN_RESTART_opcache_off](https://user-images.githubusercontent.com/20845944/71031326-faebe100-2134-11ea-8a4c-557a69694694.png)
![CLEAN_RESTART_opcache_on](https://user-images.githubusercontent.com/20845944/71031342-0212ef00-2135-11ea-93e1-f93b5aa9c8f2.png)
Stopped mining both opcache enabled/disabled if msr enabled.
Mining with opcache disabled, msr disabled, clean restart.

**Comment by xmrig** [comment] 2019-12-17 20:30
@DCress12 @aa-delite all required data received, now need some time for thinking. Thank you.

**Comment by SChernykh** [comment] 2019-12-17 20:57
@DCress12 @aa-delite Can you try `"wrmsr": ["0xc0011020:0x0", "0xc0011021:0x60", "0xc0011022:0x510000", "0xc001102b:0x1808cc16"]` in config.json? It should apply MSR mod _and_ disable opcache at the same time.

**Comment by aa-delite** [comment] 2019-12-17 21:33
> @DCress12 @aa-delite Can you try `"wrmsr": ["0xc0011020:0x0", "0xc0011021:0x60", "0xc0011022:0x510000", "0xc001102b:0x1808cc16"]` in config.json? It should apply MSR mod _and_ disable opcache at the same time.

Sure. Should opcache be enabled or disabled in BIOS to try?

**Comment by SChernykh** [comment] 2019-12-17 21:53
You can try with disabled in BIOS first, just use the same dev version. You can even try with enabled opcache, it should work too because MSR mod should disable it with these register values.

**Comment by aa-delite** [comment] 2019-12-17 22:11
Tried that string with opcache disabled. Mining well.
![registers](https://user-images.githubusercontent.com/20845944/71038640-17dbe080-2144-11ea-89b7-b0f255a458bb.png)

![newtest](https://user-images.githubusercontent.com/20845944/71038517-d1868180-2143-11ea-92ab-298a109a54c5.jpg)

**Comment by SChernykh** [comment] 2019-12-17 22:13
Thanks, I think we figured it out. The fix will be in the next release.

**Comment by DCress12** [comment] 2019-12-17 22:28
It has worked for me. Thanks for sorting this out :)

**Closed** 2019-12-17 22:28 UTC

**Comment by xxb** [comment] 2019-12-29 14:12
5.4.0 crashes anyway
I use 1700X and ASUS X370

**Comment by SChernykh** [comment] 2019-12-29 14:57
@xxb It's fixed in dev branch, wait for 5.5.0 release.

**Comment by SChernykh** [comment] 2019-12-30 10:17
@DCress12 @aa-delite XMRig 5.5.0 has a workaround for 1st gen Ryzen crashes, you should be able to mine even with enabled Opcache.
