### ISSUE TITLE
Trying to compile XMRig (Ubuntu 14.04.5 LTS)

### ISSUE THREAD

**Issue by syrius01** [xmrig/xmrig#231] opened 2017-12-01 17:20 UTC
$ make
Scanning dependencies of target cpuid
[  2%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[  4%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[  6%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[  8%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 11%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
Linking C static library libcpuid.a
[ 11%] Built target cpuid
Scanning dependencies of target xmrig
[ 13%] Building CXX object CMakeFiles/xmrig.dir/src/api/Api.cpp.o
[ 15%] Building CXX object CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o
/home/sirius/XMR/XMRIG/xmrig/src/api/ApiState.cpp: In member function ‘void ApiState::genId()’:
/home/sirius/XMR/XMRIG/xmrig/src/api/ApiState.cpp:143:53: error: no match for ‘operator<’ (operand types are ‘uv_err_t {aka uv_err_s}’ and ‘int’)
     if (uv_interface_addresses(&interfaces, &count) < 0) {
                                                     ^
/home/sirius/XMR/XMRIG/xmrig/src/api/ApiState.cpp:150:58: error: ‘uv_interface_address_t’ has no member named ‘phys_addr’
             const size_t addrSize = sizeof(interfaces[i].phys_addr);
                                                          ^
/home/sirius/XMR/XMRIG/xmrig/src/api/ApiState.cpp:154:41: error: ‘uv_interface_address_t’ has no member named ‘phys_addr’
             memcpy(input, interfaces[i].phys_addr, addrSize);
                                         ^
make[2]: *** [CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
make: *** [all] Error 2

**Comment by mxjoe** [comment] 2017-12-02 14:01
It seems like I have a similiar error on macOS 10.13.2 Beta. Please see below.

Steps to reproduce:

1. `cmake .. -DWITH_HTTPD=OFF -DUV_LIBRARY=/usr/local/opt/libuv/lib/libuv.a`
2. `make`

Result:
`[  2%] Building CXX object CMakeFiles/xmrig.dir/src/api/Api.cpp.o
In file included from /Users/joe/Documents/Software/Mining/xmrig-mac/xmrig/src/api/Api.cpp:24:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not
      found
#include_next <string.h>
              ^~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/xmrig.dir/src/api/Api.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
make: *** [all] Error 2`

**Comment by abale** [comment] 2017-12-03 15:16
I think it is due to an older version of libuv.  I have this same error with libuv 0.10

```
[ 15%] Building CXX object CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o
/root/stak/xmrig-2.4.3/src/api/ApiState.cpp: In member function ‘void ApiState::genId()’:
/root/stak/xmrig-2.4.3/src/api/ApiState.cpp:143:53: error: no match for ‘operator<’ (operand types are ‘uv_err_t {aka uv_err_s}’ and ‘int’)
     if (uv_interface_addresses(&interfaces, &count) < 0) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/root/stak/xmrig-2.4.3/src/api/ApiState.cpp:150:58: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             const size_t addrSize = sizeof(interfaces[i].phys_addr);
                                                          ^~~~~~~~~
/root/stak/xmrig-2.4.3/src/api/ApiState.cpp:154:41: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             memcpy(input, interfaces[i].phys_addr, addrSize);
                                         ^~~~~~~~~
make[2]: *** [CMakeFiles/xmrig.dir/src/api/ApiState.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig.dir/all] Error 2
```

**Comment by abale** [comment] 2017-12-03 15:21
Fixed by doing this:

```
sudo apt-get install make automake libtool curl
curl -sSL https://github.com/libuv/libuv/archive/v1.8.0.tar.gz | sudo tar zxfv - -C /usr/local/src
cd /usr/local/src/libuv-1.8.0
sudo sh autogen.sh
sudo ./configure
sudo make
sudo make install
sudo rm -rf /usr/local/src/libuv-1.8.0 && cd ~/
sudo ldconfig``


then build with:

```
rm -rf CMakeFiles
rm -rf CMakeCache.txt
cmake -DWITH_HTTPD=OFF -DUV_LIBRARY=/usr/local/lib/libuv.so .
make clean
make```

**Comment by howTOdoIT2** [comment] 2017-12-08 21:09
why the developer dont make a ubuntu 14.04 version ...why we need to compile it??
I just want a version of xmrig for ubuntu like is one for windows... very simple

**Comment by howTOdoIT2** [comment] 2017-12-08 21:19
from what do I read here...it's seams that you remove the donation feature ... ain't that right   abale ?
:))))

**Closed** 2018-03-14 23:31 UTC
