### ISSUE TITLE
Terminal quits without any 

### ISSUE THREAD

**Issue by ktalebian** [xmrig/xmrig#2864] opened 2022-01-15 00:49 UTC
**Describe the bug**
When I try to run the application, I get the following:

```
Last login: Fri Jan 14 16:45:43 on ttys001
/Applications/xmrig/xmrig ; exit;

~ 
➜ /Applications/xmrig/xmrig ; exit;
 * ABOUT        XMRig/6.16.2 clang/10.0.0
 * LIBS         libuv/1.41.0 OpenSSL/1.1.1k hwloc/2.5.0
 * HUGE PAGES   supported
 * 1GB PAGES    unavailable
 * CPU          Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (1) 64-bit AES
                L2:1.5 MB L3:12.0 MB 6C/12T NUMA:1
 * MEMORY       13.5/16.0 GB (85%)
[1]    27630 killed     /Applications/xmrig/xmrig
Saving session...completed.

[Process completed]
```

Nothing else is explained - I have no idea why this is not working. Help is appreciated.

**Comment by SChernykh** [comment] 2022-01-15 17:17
`MEMORY       13.5/16.0 GB (85%)`
Maybe you don't have enough free memory and system's OOM killer terminates XMRig because of that.

**Comment by UnixCro** [comment] 2022-01-28 12:50
Duplicate of https://github.com/xmrig/xmrig/issues/2421
Thank you

**Closed** 2023-08-04 22:56 UTC
