### ISSUE TITLE
Is this a bug or a feature? 

### ISSUE THREAD

**Issue by Maz4id** [xmrig/xmrig#1995] opened 2020-12-22 09:00 UTC
Today I wanted to compile Xmrig again because I had an old version of it v6.4.0. 
I always use at cmake `-DWITH_EMBEDDED_CONFIG=ON ` and background true inside the config. 
After I finished and tried to start it, I saw that there is no error message and it goes right into background.
It used to say: unable to open config.json or something like that.
So that message is removed now if ur using embedded config option?
Personally, I love it because you can run xmrig again with 'systemd'. It used to fail the service because of that error message.

**Comment by xmrig** [comment] 2020-12-22 09:05
Seems related #1930
Can you show your service file? Thank you.

**Comment by Maz4id** [comment] 2020-12-22 09:22
It works If the executable path is prefixed with "-"so I don't have any problems running it.
But again, the error message is removed now on embedded config option or is a bug?

**Comment by xmrig** [comment] 2020-12-22 09:32
Message not removed, but since v6.5.0 with #1925 there should be 3 messages instead of 1, not sure how it breaks systemd compatibility, but you are the second who reported it. I asked about the service file to try reproduce the issue.
Thank you.

**Comment by Maz4id** [comment] 2020-12-22 10:36
Here is a video of how I compiled xmrig on centos 7 and you can clearly see at the end that there's no message about config or anything. It goes to background instantly. 
Maybe it helps if ur saying that the message is not removed.
https://youtu.be/Xw-_3Je5Ln0

**Comment by xmrig** [comment] 2020-12-22 14:47
Fixed in dev branch, this was regression with v6.7.0, log was not initialized on such an early phase.

P.S. Please don't use `-DBUILD_STATIC=ON` option, it only work as expected with musl libc for example on [Alpine](https://xmrig.com/docs/miner/build/alpine) your executable will crash on other OS because not all functions was added https://i.imgur.com/6qu6jch.png

**Closed** 2020-12-22 21:31 UTC
Labels: bug
