### ISSUE TITLE
Ryzen 7 1700x Crach/freeze

### ISSUE THREAD

**Issue by Advantage1** [xmrig/xmrig#1588] opened 2020-03-08 12:27 UTC
**Describe the bug**
When diff is grow more when 90k
ver 5.3.0-msvc is crached
ver 5.4+-msvc is freezed, speed down to 10-12 on each core

ver 5.8.2-gcc - work stable

**Required data**
 - xmrig.exe -o gulf.moneroocean.stream:10016 -u *** -p **:**@**.** --donate-level=1
 - Windows 10
 - Ryzen 7 1700x

**Comment by cryptonius** [comment] 2020-03-20 14:28
I've noticed the app closing on me out of a sudden. Ryzen 3600 here.

**Comment by Spudz76** [comment] 2020-03-23 06:22
#1506 probably related / caused by new Win10 19xx patch cpu scheduler changes

Set threads to `-1` all the way across (no hard binding to cores) and don't use `priority` setting

**Comment by xmrig** [comment] 2020-08-31 05:47
https://xmrig.com/docs/miner/randomx-stability-troubleshooting-guide

**Closed by xmrig** 2020-08-31 05:47 UTC
Labels: stability
