### ISSUE TITLE
Build Never finishes in CentOS

### ISSUE THREAD

**Issue by attackjoker11** [xmrig/xmrig#267] opened 2017-12-16 09:06 UTC
build]# cmake .. -DCMAKE_BUILD_TYPE=Release -DUV_LIBRARY=/usr/lib64/libuv.a
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    cmake/cpu.cmake

CMake Error at CMakeLists.txt:158 (find_package):
  By not providing "FindUV.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "UV", but CMake did
  not find one.

  Could not find a package configuration file provided by "UV" with any of
  the following names:

    UVConfig.cmake
    uv-config.cmake

  Add the installation prefix of "UV" to CMAKE_PREFIX_PATH or set "UV_DIR" to
  a directory containing one of the above files.  If "UV" provides a separate
  development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/root/xmrig/build/CMakeFiles/CMakeOutput.log".

**Comment by siftycat** [comment] 2017-12-19 02:04
Error is caused by missing libuv-devel. This should be installed as a dependency of libuv-static. So `yum install libuv-static` or `yum install libuv-devel`.

**Comment by biaxz** [comment] 2018-01-07 06:20
Duplicate of #170

**Closed** 2018-03-14 23:40 UTC
Labels: libuv
